export const SPREADSHEET_ID = '1uRAsFCpGXVexzKG2Mkxt43ryhdo9bff56r_AKcxhAcs'
export const TYPES_TAB_NAME = 'types'
export const TRANSLATION_TAB_NAME = 'translations'
export const OPENSHEET_URI = 'https://opensheet.elk.sh'
export const GOOGLE_DRIVE_URI = 'https://drive.google.com/uc?export=view&id='
export const BRAND_NAME = 'משתלת שהם'
export const BACKGROUND_COLOR = '#084b3f'
export const PHONE_NUMBER = '+16194334285'
export const EMAIL_ADDRESS = 'thehobbit85@gmail.com'
